<DOCTYPE html>
    <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head>
        <title></title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <!--[if mso]><xml></xml><![endif]--><style>
            *{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none} @media (max-width:660px){.social_block.desktop_hide .social-table{display:inline-block!important}.fullMobileWidth,.image_block img.big,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
        </style>
    </head>
    <body style="background-color:#e8e8e8;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none">
    <table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#e8e8e8"><tbody><tr><td>
                <table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:15px;padding-left:15px;padding-right:15px;padding-top:15px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="html_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td class="pad"><div style="font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif;text-align:center" align="center"><div style="display:none;font-size:1px;color:#333333;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">

                                                            Мы рады, что ваш ребенок будет посещать наши онлайн-занятия. Мы зарегистрировали вас на нашей платформе, в этом письме находится доступ и ссылка.

                                                        </div></div></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"></td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="fullMobileWidth" src="https://img.hiteml.com/en/v5/user-files?userId=2402259&amp;resource=himg&amp;disposition=inline&amp;name=66nm695gqneqguz367c6xzasc3f53xyejhheobse9qbs1jchn1ry3y8nrkwnu98ytgnmb9nzqcybygb3198a7y7gttc" style="display:block;height:auto;border:0;width:640px;max-width:100%" width="640"></div></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0">
                                            <tbody><tr><td class="pad" style="padding-left:30px;padding-right:30px;width:100%"><div class="alignment" align="center" style="line-height:10px">
                                                        <a href="https://designaeasy.ru/education/ed/signin/signin.php" target="_blank" style="outline:none" tabindex="-1"><img class="big" src="https://img.hiteml.com/en/v5/user-files?userId=2402259&amp;resource=himg&amp;disposition=inline&amp;name=6cz51n67de6xuzz367c6xzasc3f53xyejhheobse9qbs1jchn1ry6hmx4zwry3j9osmooya37kbbo3hbbchjtywf8jw" style="display:block;height:auto;border:0;width:580px;max-width:100%" width="580" alt="Регистрация на пробный курс" title="Регистрация на пробный курс"></a>
                                                    </div></td></tr>
                                            </tbody></table></td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0">
                                        <div class="spacer_block block-1" style="height:30px;line-height:30px;font-size:1px"> </div>
                                        <table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad" style="padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:15px"><div style="font-family:sans-serif"><div class="" style="font-size:12px;mso-line-height-alt:24px;color:#000;line-height:2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif">
                                                            <p style="margin:0;font-size:12px;mso-line-height-alt:48px">
                                                                <span style="font-size:24px;"><strong>Здравствуйте!</strong></span></p>
                                                            <p style="margin:0;font-size:12px;mso-line-height-alt:24px">&nbsp;</p>
                                                            <p style="margin:0;font-size:12px;mso-line-height-alt:30px"><span style="font-size:15px;">Мы рады, что ваш ребенок будет посещать наши онлайн-занятия. Мы зарегистрировали вас на нашей платформе, в этом письме находится доступ и ссылка. Советуем вам сразу изменить пароль на удобный для вас в настройках вашего профиля.</span></p>
                                                            <p style="margin:0;font-size:12px;mso-line-height-alt:24px">&nbsp;</p>
                                                        </div></div></td></tr></tbody></table>
                                        <table class="text_block block-8" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad" style="padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:15px"><div style="font-family:sans-serif">
                                                        <div class="" style="font-size:12px;mso-line-height-alt:24px;color:#000;line-height:2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif"><p style="margin:0;font-size:12px;mso-line-height-alt:48px"><span style="font-size:24px;"><strong>Доступ на платформу "DesignNaEasy"</strong></span></p></div>
                                                    </div></td></tr></tbody></table>
                                    </td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#3aaee0;color:#000;border-bottom:2px dotted #0068a5;border-left:2px dotted #0068a5;border-radius:0;border-right:2px dotted #0068a5;border-top:2px dotted #0068a5;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:5px;vertical-align:middle;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad" style="padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:15px"><div style="font-family:sans-serif"><div class="" style="font-size:12px;mso-line-height-alt:24px;color:#fff;line-height:2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif">
                                                            <p style="margin:0;text-align:center;mso-line-height-alt:30px"><span style="font-size:15px;"><strong>Логин: </strong> <a style="color:white;font-weight: 800;">{{$email}}</a></span></p>
                                                            <p style="margin:0;text-align:center;mso-line-height-alt:30px"><span style="font-size:15px;"><strong>Пароль: </strong><span style="color:white;font-weight: 800;">{{$password}}</span></span></p>
                                                            <p style="margin:0;text-align:center;mso-line-height-alt:30px"><span style="font-size:15px;"><strong>Ссылка на подключение: </strong><a href="{{route("login")}}" style="color:white;font-weight: 800;">{{route("login")}}</a></span></p>
                                                        </div></div></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>

            </td></tr></tbody></table></td></tr></tbody></table>
    <table class="row row-8" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:640px" width="640"><tbody><tr>
                        <td class="column column-1" width="41.666666666666664%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><a href="{{route("login")}}" target="_blank" style="outline:none" tabindex="-1"><img src="https://img.hiteml.com/en/v5/user-files?userId=2402259&amp;resource=himg&amp;disposition=inline&amp;name=6rudp6eshk5s8tz367c6xzasc3f53xyejhheobse9qbs1jchn1ry51hdgxjf1aekqcboozq9xrasqdm5k64youwu11u6xzg6i4ghqf867dmdb7qpcxn9nmdpyh9sp31s4" style="display:block;height:auto;border:0;width:207px;max-width:100%" width="207"></a></div></td></tr></tbody></table></td>
                        <td class="column column-2" width="58.333333333333336%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad" style="padding-bottom:15px;padding-right:30px;padding-top:15px"><div style="font-family:sans-serif"><div class="" style="font-size:12px;mso-line-height-alt:24px;color:#000;line-height:2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif"><p style="margin:0;mso-line-height-alt:24px">Если у вас возникли технические сложности с подключением к нашей онлайн-платформе, напишите в техническую поддержку:<br>
                                                    Email: <strong><a href="mailto:designaeasy@gmail.com" title="designaeasy@gmail.com" rel="noopener noreferrer" target="_blank" style="text-decoration: underline; color: #0068A5;">designaeasy@gmail.com</a></strong><br>
                                                    Telegram-бот:&nbsp;<strong><a href="https://t.me/designaeasy_bot" target="_blank" style="text-decoration: underline; color: #0068A5;" rel="noopener"><span style="" id="1d28029a-18f5-4e4a-ae62-9f3f211dbdad">@designaeasy_bot</span></a></strong></p></div></div></td></tr></tbody></table></td>
                    </tr></tbody></table></td></tr></tbody></table>
    <table class="row row-9" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#3aaee0;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:middle;border-top:0;border-right:0;border-bottom:0;border-left:0">
                            <table class="social_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td class="pad"><div class="alignment" align="center"><table class="social-table" width="108px" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block"><tbody><tr>
                                                    <td style="padding:0 2px 0 2px"><a href="https://vk.com/designaeasy" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/vkontakte@2x.png" width="32" height="32" alt="Vkontakte" title="Vkontakte" style="display:block;height:auto;border:0"></a></td>
                                                    <td style="padding:0 2px 0 2px">
                                                        <a href="https://t.me/designaeasy_bot" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/telegram@2x.png" width="32" height="32" alt="Telegram" title="Telegram" style="display:block;height:auto;border:0"></a>
                                                    </td>
                                                    <td style="padding:0 2px 0 2px"><a href="https://api.whatsapp.com/send?phone=79047532291" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-only-logo-white/whatsapp@2x.png" width="32" height="32" alt="WhatsApp" title="WhatsApp" style="display:block;height:auto;border:0"></a></td>
                                                </tr></tbody></table></div></td></tr></tbody></table>
                            <table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad" style="padding-bottom:10px;padding-left:25px;padding-right:10px;padding-top:20px"><div style="font-family:sans-serif"><div class="" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#fff;line-height:1.2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif">
                                    </td></tr></tbody></table></td></tr></tbody></table>
                <table class="row row-10" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#dbf3ff;color:#000;width:640px" width="640"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0">
                                        <table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><img class="fullMobileWidth" src="https://img.hiteml.com/en/v5/user-files?userId=2402259&amp;resource=himg&amp;disposition=inline&amp;name=6r8u18hjxb6gitz367c6xzasc3f53xyejhheobse9qbs1jchn1ryaho7er8sh5skidwg7kapeqhijjdfidci41ijwda" style="display:block;height:auto;border:0;width:640px;max-width:100%" width="640"></div></td></tr></tbody></table>
                                        <table class="text_block mobile_hide block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tbody><tr><td class="pad"><div style="font-family:sans-serif"><div class="" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2;font-family:Montserrat,Trebuchet MS,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Tahoma,sans-serif">
                                                            <p style="margin:0;mso-line-height-alt:14.399999999999999px">&nbsp;</p>
                                                            <p style="margin:0;mso-line-height-alt:14.399999999999999px">&nbsp;</p>
                                                            <p style="margin:0;mso-line-height-alt:14.399999999999999px">&nbsp;</p>
                                                            <p style="margin:0;mso-line-height-alt:14.399999999999999px">&nbsp;</p>
                                                        </div></div></td></tr></tbody></table>
                                    </td></tr></tbody></table></td></tr></tbody></table>
            </td></tr></tbody></table>
    </body></html>
